### ISSUE TITLE
conv2d implementation

### ISSUE THREAD

**Issue by mf27** [naturomics/CapsLayer#12]
I just have a short comment on the implementation of the convolutional capsule layer (in `layers.py`):
shouldn't it just be based on the existing (ordinary) convolutional layer, there is no need for rewriting from scratch? See [https://github.com/XifengGuo/CapsNet-Keras/blob/540f15dfc531c3e82f76fbae7de72bb9e48ae72a/capsulelayers.py](https://github.com/XifengGuo/CapsNet-Keras/blob/540f15dfc531c3e82f76fbae7de72bb9e48ae72a/capsulelayers.py)
Your implementation seems, as you say yourself, very inefficient (and unnecessary?)...

**Comment by naturomics** [comment]
I think you misunderstood. Conv2d in layers.py is the implement of [EM Routing between Capsules](https://openreview.net/pdf?id=HJWLfGWRb), which we call *convolutional capsule layer* and a completely new thing, different from the *existing convolutional layer*.
