### ISSUE TITLE
CapsNet on RGB 256*256 data

### ISSUE THREAD

**Issue by deep0learning** [naturomics/CapsLayer#5]
Can you tell us please how can we apply your network to classify RGB 256*256 data.

The structure of my datasets is:

Train:
  Class 1:  
             0001.jpg
             0002.jpg
             0003.jpg   
Class 2:     
             0001.jpg
             0002.jpg
             0003.jpg   
Thank you so much in advanced.

**Comment by naturomics** [comment]
@deep0learning What do you think the difference is between RGB image and gray image? All you need is just change the channels from 1 to 3 in this [line](https://github.com/naturomics/CapsLayer/blob/fe305cef4ce29653b4dac2d80c23a331f1277f2a/models/main.py#L124).

**Comment by movefast** [comment]
You'll probably also want to change the channel num during [recon](https://github.com/naturomics/CapsLayer/blob/fe305cef4ce29653b4dac2d80c23a331f1277f2a/models/vectorCapsNet.py#L119)  as well for the same reason naturomics mentioned; otherwise, you'll likely run into some reshaping errors.

**Comment by naturomics** [comment]
@movefast It's replaced with variables now, no need to modify these lines

**Comment by deep0learning** [comment]
@naturomics Thank you so much. Actually I am new at programming. Can you please tell me how can we feed our data? I am not sure that how can we feed our data to this network?

**Comment by naturomics** [comment]
@deep0learning Write your own data load function like this [`losd_mnist`](https://github.com/naturomics/CapsLayer/blob/1709caceccd183bf800262ade12729278cc12165/capslayer/utils.py#L30) or this [`load_fashion_mnist`](https://github.com/naturomics/CapsLayer/blob/1709caceccd183bf800262ade12729278cc12165/capslayer/utils.py#L64), and add it to the function [`load_data`](https://github.com/naturomics/CapsLayer/blob/1709caceccd183bf800262ade12729278cc12165/capslayer/utils.py#L102) and [`get_batch_data`](https://github.com/naturomics/CapsLayer/blob/1709caceccd183bf800262ade12729278cc12165/capslayer/utils.py#L113)

**Comment by Ahmedest61** [comment]
In some case, when using data equal or greater then 128x128 RGB, it may come across the problem of **Cannot create a tensor proto whose content is larger than 2GB** when you run **tf.train.slice_input_producer([trX, trY])** as in this code or in some capsulenet, when ** self.sess.run(tf.global_variables_initializer())** runs, the system memory shoots up and code get crash all the time :(
